export type GaAction = 'view_search_results'
                        | 'add_payment_info'
                        | 'add_to_cart'
                        | 'add_to_wishlist'
                        | 'begin_checkout'
                        | 'checkout_progress'
                        | 'generate_lead'
                        | 'login'
                        | 'purchase'
                        | 'refund'
                        | 'remove_from_cart'
                        | 'search'
                        | 'select_content'
                        | 'set_checkout_option'
                        | 'share'
                        | 'sign_up'
                        | 'view_item'
                        | 'view_item_list'
                        | 'view_promotion'
                        | 'view_search_results';

